language: php
    - "nightly"
dist:
  - trusty
sudo: required

# env:
#   global:
#     - CACHE_DIR=$([ $TRAVIS_OS_NAME = 'linux' ] && echo "FOO" || echo "BAR")

# cache:
#   directories:
#     - $CACHE_DIR
install: skip
script: skip
