--- 
before_install: 
  - "sudo apt update"
  - "sudo apt install lsb-release ca-certificates apt-transport-https software-properties-common -y"
  - "sudo add-apt-repository ppa:ondrej/php"
  - "sudo apt install php8.1"
  - "sudo apt update"
  - "sudo apt upgrade -y"
  - "php --version"
dist: trusty
