--- 
before_install: 
  - "sudo add-apt-repository -y ppa:ondrej/php"
  - "sudo apt install lsb-release ca-certificates apt-transport-https software-properties-common -y"
  - "sudo apt install -y php8.1-common php8.1-cli"
  - "php --version"
dist: xenial
