--- 
dist: focal
sudo: required
before_install: 
  - "sudo apt install php8.1 php8.1-common php8.1-gd php8.1-mysql php8.1-imap php8.1-cli php8.1-cgi libapache2-mod-fcgid apache2-suexec-pristine php-pear imagemagick libruby libapache2-mod-python php8.1-curl php8.1-intl php8.1-pspell php8.1-sqlite3 php8.1-tidy php8.1-xsl memcached php-memcached php-memcache php8.1-imagick php8.1-zip php8.1-mbstring php8.1-opcache php8.1-ldap php8.1-soap php8.1-bz2 php8.1-bcmath php8.1-xml php8.1-fpm php8.1-phpdbg php-apcu php-apcu-bc php8.1-readline libapache2-mod-php8.1 pkg-php-tools shtool xml2 dh-php dh-make libphp8.1-embed php-geoip php8.1-pgsql php8.1-dev php-xdebug" 

