---
addons:
  apt:
    packages:
    sources:
      - sourceline: "ppa:ondrej/php"
      - sourceline: "deb http://ftp.de.debian.org/debian sid main"
    update: true
before_install:
  - "sudo apt update"
  - "sudo apt-get -y install libxml2-dev"
  - "sudo apt install -y lsb-release ca-certificates apt-transport-https software-properties-common gnupg2"
  - echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/sury-php.list"
  - "wget -qO - https://packages.sury.org/php/apt.gpg | sudo apt-key add -"
   
dist: focal
install: skip
language: php
