--- 
dist: focal
sudo: required
before_install: 
  - "sudo locale-gen en_US.UTF-8"
  - "sudo export LANG=en_US.UTF-8"
  - "sudo export LC_ALL=en_US.UTF-8"
  - "sudo apt-get install software-properties-common"
  - "sudo add-apt-repository ppa:ondrej/php"
  - "sudo apt-get update"
  - "sudo apt-get upgrade"
  - "sudo apt install php8.1"
