sudo: false
php:
  - 8.0
  - nightly

before_install:
        - sudo rm -rf /var/lib/apt/lists/lock /var/cache/apt/archives/lock /var/lib/dpkg/lock
        - sudo apt-get update
        - sudo apt-get -y install libcurl4-openssl-dev
        - if [[ $VERSION =~ ^8.1 ]]; then sudo apt-get -y install argon2 libargon2-0 libargon2-0-dev; fi
        - sudo ln -s /usr/include/x86_64-linux-gnu/curl/ /usr/local/include
        - command -v expect || sudo apt-get install expect

install: skip
