---
addons:
  apt:
    packages: php8.1
    sources:
      - sourceline: "ppa:ondrej/php"
    update: true
before_install:
  - "sudo apt-get -y install libxml2-dev"
  - "sudo apt install lsb-release ca-certificates apt-transport-https software-properties-common -y"
dist: xenial
install: skip
language: php
