dist: focal
language: php
php:
  - 8.0
  - nightly

before_install:
        - sudo apt update
        - sudo apt install lsb-release ca-certificates apt-transport-https software-properties-common -y
        - sudo apt install php8.1

install: skip
